auto

diff --git a/config/todo/actions/e b/config/todo/actions/e
--- a/config/todo/actions/e
+++ b/config/todo/actions/e
@@ -14,11 +14,21 @@ error_handler
 old=$(awk "NR == $num {print; exit}" "$TODO_FILE")
 printf 'old: %s\n' "$old"
 # standard IFS trims whitespace, empty -- preserves
-read -e -i "$old" -p 'new: ' -r new
+read -e -i "$old" -p 'new: ' -r new || {
+	echo "Read error"
+	exit 1
+}
 
 [ "$new" = "$old" ] || [[ $new =~ ^\s*$ ]] && {
 	echo "No changes"
 	exit 0
 }
 
-awk -v "new=$new" -- "NR == $num {sub(/.*/, new)}; {print}" "$TODO_FILE" | sponge "$TODO_FILE" && echo "Saved"
+awk -v "new=$new" -- "NR == $num {sub(/.*/, new)}; {print}" "$TODO_FILE" | sponge "$TODO_FILE" && {
+	echo "Saved"
+	exit 0
+}
+
+echo "Save error"
+exit 1
+
